packages:
  - ./
  - playground
  - docs
  - demo

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@nuxt/*'
  - nuxt
